### ISSUE TITLE
Data should not be stored in `.config`

### ISSUE THREAD

**Issue by Leon-Plickat** [beatbrot/trackie#11]
Currently the times trackie tracks are stored in `~/.config`. However that directory is intended solely for configuration files, not data. 

Instead `XDG_DATA_HOME` is the idiomatic location for data on modern Linux (it usually defaults to `~/.local/share`).

**Comment by beatbrot** [comment]
Thanks for your suggestion!

I have to say, that I am in no way an expert on Linux, so I need a few more hints on this :)

When I am using `XDG_DATA_HOME` and it points to `~/.local/share/`, then the path of my `trackie.json` would be `~/.local/share/trackie.json`, right?

**Comment by Leon-Plickat** [comment]
> When I am using XDG_DATA_HOME and it points to ~/.local/share/, then the path of my trackie.json would be ~/.local/share/trackie.json, right?

That works, but it would be more idiomatic to create a `trackie` directory there and place the data file inside it. The idea is that if in the future trackie needs more than one file, they are all neatly in the same place.

**Comment by Leon-Plickat** [comment]
Bonus points for migrating the old data, good idea!
