### ISSUE TITLE
Add a `resume` command

### ISSUE THREAD

**Issue by beatbrot** [beatbrot/trackie#13]
**Is your feature request related to a problem? Please describe.**
Often times, time tracking has to be stopped and later resumed because something had to be done real quick. The user then has to search for the exact name of the project he previously worked on and re-type `trackie start <project-name>`.

**Describe the solution you'd like**
There should be a `trackie resume` command that starts tracking time for the project whose time-tracking was stopped last.

Example-Workflow:

```
> trackie start "my-app"
Tracking my-app...
> trackie stop "my-app"
Stop tracking my-app
> trackie resume
"Tracking my-app" 
```

**Describe the usecase of your feature**
Someone could, e.g. work on a project but was interrupted by a phone call. He then can just type `trackie resume` to resume his work on the project.

**Comment by beatbrot** [comment]
@Leon-Plickat Do you have an opinion on this? Could this be a good feature?

**Comment by Leon-Plickat** [comment]
I'd really like to have this feature!
