### ISSUE TITLE
[feature request] `trackie report` should be able to output json

### ISSUE THREAD

**Issue by Leon-Plickat** [beatbrot/trackie#16]
I would like to use the data trackie collects with external purposes (I'd like to plot how much time a day I spend working).

While it is possible to parse the data file with other tools, I'd have to re-implement what trackie already does: defragmenting the time blogs and turning a bunch of start and end times into time spans.

It would be pretty nice if trackie could optionally output a machine parseable format (probably JSON) when using `trackie report`.

Something like this (time in minutes):
``` sh
$ trackie report -j
{
     "days": [
          "2021-08-10": {
              "total": 320,
              "projects": [
                   {
                        "name": "my fancy project",
                        "time": 100
                   },
                   {
                        "name": "my other project",
                        "time": 220
                   }
              ]
          }
     ]
}

**Comment by beatbrot** [comment]
Good idea! I'll implement this in the next weeks :)
